"""
evaluate.py
───────────
Offline evaluation of the face recognition system.

Performs leave-one-out cross-validation across the database images
and reports accuracy, precision, recall, F1, and a confusion matrix.

Usage:
    python evaluate.py [--threshold 0.65]
"""
#test edit
import os, pickle, argparse
from tkinter.font import names
import numpy as np
from sklearn.metrics import (accuracy_score, precision_score,
                              recall_score, f1_score, confusion_matrix,
                              ConfusionMatrixDisplay)
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from datetime import datetime

EMBEDDINGS_FILE = 'embeddings.pkl'

def database_load():
    # Check file exists before trying to load
    if not os.path.exists(EMBEDDINGS_FILE):
        print("[ERR] No embeddings file found. Run face_system.py --rebuild first.")
        return None, None, {}

    with open(EMBEDDINGS_FILE, 'rb') as f:
        database: dict = pickle.load(f)

    if len(database) < 2:
        print("[ERR] Need at least 2 identities in the database.")
        return None, None, {}

    # Find the smallest class size
    min_count = min(len(embs) for embs in database.values())
    print(f"Balancing all classes to {min_count} embeddings (smallest class size)")

    # Cap everyone to that size
    import random
    database = {
        name: random.sample(embs, min_count)
        for name, embs in database.items()
    }

    print("Embeddings per person after balancing:")
    for name, embs in database.items():
        print(f"  {name}: {len(embs)}")

    names = sorted(database.keys())

    # Load filename map if available — generated by build_database in face_system.py
    # Used to trace misclassifications back to their source image file
    filename_map = {}
    if os.path.exists('filenames.pkl'):
        with open('filenames.pkl', 'rb') as f:
            filename_map = pickle.load(f)
    else:
        print("[WARN] filenames.pkl not found — misclassification report will show indices only")

    return names, database, filename_map

def evaluate(threshold: float = 0.65, names=None, database=None, filename_map={}):
    y_true, y_pred = [], []
    labels_present, *_ = loocv(names, y_true, y_pred, threshold, database, filename_map)

    # 5. Confusion Matrix Plot
    # Generates a visual heatmap showing correct predictions and misclassifications (false positives/negatives).
    cm = confusion_matrix(y_true, y_pred, labels=labels_present)
    fig, ax = plt.subplots(figsize=(max(6, len(labels_present)), max(5, len(labels_present))))
    disp = ConfusionMatrixDisplay(cm, display_labels=labels_present)
    disp.plot(ax=ax, colorbar=False, xticks_rotation=45)
    ax.set_title(f'Confusion Matrix (threshold={threshold})', fontsize=13)
    plt.tight_layout()
    out_path = 'confusion_matrix.png'
    plt.savefig(out_path, dpi=120)
    print(f"\n[INFO] Confusion matrix saved to {out_path}")

def loocv(names, y_true, y_pred, threshold, database, filename_map={}):
    # Track all misclassifications for post-evaluation reporting
    # Each entry stores the true name, predicted name, embedding index and confidence score
    misidentified: list[dict] = []

    for true_name in names:
        embs = database[true_name]
        for i, probe_emb in enumerate(embs):
            # 1. Leave-One-Out Cross Validation
            # We treat the current image (probe_emb) as an unknown face to be tested,
            # and train the system using the remaining images of this person.
            gallery = {}
            for n, e in database.items():
                # Exclude the current test image using its index 'i'
                others = [x for j, x in enumerate(e) if not (n == true_name and j == i)]
                if others:
                    # Calculate the average embedding (face features) for this person
                    gallery[n] = np.mean(others, axis=0)

            # 2. Recognition Phase
            # Compare the test image (probe_emb) against the calculated gallery
            p_emb = probe_emb.reshape(1, -1)
            best_name, best_score = 'Unknown', 0.0
            
            # Find the most similar identity in the gallery
            for n, g_emb in gallery.items():
                # Measure image similarity using Cosine Distance
                sim = float(cosine_similarity(p_emb, g_emb.reshape(1, -1))[0][0])
                if sim > best_score:
                    best_score, best_name = sim, n
                    
            # If the best matching score is lower than the threshold, mark as 'Unknown'
            if best_score < threshold:
                best_name = 'Unknown'

            # If prediction was wrong for any reason (wrong person or Unknown),
            # record it for the misclassification report
            if best_name != true_name:
                misidentified.append({
                    'true_name': true_name,
                    'predicted': best_name,
                    'embedding_index': i,
                    'best_score': best_score
                })

            # Save the true identity and the predicted identity for final evaluation
            y_true.append(true_name)
            y_pred.append(best_name)

    all_labels = names + ['Unknown']
    labels_present = sorted(set(y_true + y_pred))

    # 3. Calculate Evaluation Metrics (Accuracy, Precision, Recall, F1 Score)
    # These metrics determine how well the evaluation performed across all test subsets.
    acc = accuracy_score(y_true, y_pred)
    pre = precision_score(y_true, y_pred, labels=names,
                        average='macro', zero_division=0)
    rec = recall_score(y_true, y_pred, labels=names,
                    average='macro', zero_division=0)
    f1  = f1_score(y_true, y_pred, labels=names,
                average='macro', zero_division=0)

    print("\n══════════════════════════════════════════")
    print(f"  Leave-One-Out Evaluation (threshold={threshold})")
    print("══════════════════════════════════════════")
    print(f"  Identities   : {len(names)}")
    print(f"  Total probes : {len(y_true)}")
    print(f"  Accuracy     : {acc*100:.2f}%")
    print(f"  Precision    : {pre*100:.2f}%  (macro, known only)")
    print(f"  Recall       : {rec*100:.2f}%  (macro, known only)")
    print(f"  F1 Score     : {f1*100:.2f}%  (macro, known only)")

    unknown_rate = sum(1 for p in y_pred if p == 'Unknown') / len(y_pred)
    print(f"  Unknown rate : {unknown_rate*100:.2f}%")
    print("══════════════════════════════════════════\n")

    # 4. Per-person breakdown
    # Displays individual accuracy statistics for each person in the database.
    print(f"{'Name':<20} {'Total':>6} {'Correct':>8} {'Acc':>8}")
    print("─" * 46)
    for n in names:
        idxs   = [i for i, t in enumerate(y_true) if t == n]
        correct = sum(1 for i in idxs if y_pred[i] == n)
        total   = len(idxs)
        print(f"{n:<20} {total:>6} {correct:>8} {correct/total*100:>7.1f}%")

    # 5. Misclassification Report
    # Lists every embedding that was incorrectly identified, including source filename
    # if filenames.pkl is available from build_database
    if misidentified and threshold == 0.65:
        print("\n══════════════════════════════════════════")
        print("  Misclassified Embeddings")
        print("══════════════════════════════════════════")
        print(f"{'True Name':<20} {'Predicted':<20} {'File':<30} {'Aug':>5} {'Score':>8}")
        print("─" * 86)
        for m in misidentified:
            # Look up source filename if filename map was loaded from filenames.pkl
            if filename_map and m['true_name'] in filename_map:
                info = filename_map[m['true_name']][m['embedding_index']]
                # aug 0 = original image, aug 1-5 = augmented versions
                aug_label = 'orig' if info['augment'] == 0 else f"aug{info['augment']}"
                fname_str = info['file']
            else:
                # Fall back to index only if filename map not available
                fname_str = 'N/A'
                aug_label = 'N/A'
            print(f"  {m['true_name']:<20} {m['predicted']:<20} "
                  f"{fname_str:<30} {aug_label:>5} {m['best_score']:>8.4f}")

    
        # Summary by person — highlights who is hardest to recognise
        print(f"\n  Misclassifications per person:")
        for name in names:
            count = sum(1 for m in misidentified if m['true_name'] == name)
            if count > 0:
                print(f"    {name}: {count}")
        print(f"\n  Total misclassified: {len(misidentified)}")
        print("══════════════════════════════════════════\n")
    elif threshold != 0.65:
        print("Skipping misclassified files for non 0.65 thresholds.")
    else:
        print("\n[INFO] No misclassifications found.")
    

    return labels_present, acc, pre, rec, f1, unknown_rate

def evaluate_threshold_range(thresholds: list[float], names, embs):
    """Run evaluate() across multiple thresholds and plot results."""

    with open(EMBEDDINGS_FILE, 'rb') as f:
        database: dict = pickle.load(f)

    results = {
        'threshold': [],
        'accuracy': [],
        'precision': [],
        'recall': [],
        'f1': [],
        'unknown_rate': []
    }

    # Per-person accuracy at each threshold — {name: [acc_at_t1, acc_at_t2, ...]}
    per_person: dict[str, list[float]] = {name: [] for name in names}

    for t in thresholds:
        y_true, y_pred = [], []

        print(f"Testing threshold {t:.2f}...")
        # Run same LOOCV logic but return metrics instead of printing
        labels_present, acc, pre, rec, f1, unk = loocv(names, y_true, y_pred, t, database)
        results['threshold'].append(t)
        results['accuracy'].append(acc)
        results['precision'].append(pre)
        results['recall'].append(rec)
        results['f1'].append(f1)
        results['unknown_rate'].append(unk)

        # Extract per-person accuracy from y_true and y_pred directly
        # Same calculation as the per-person breakdown printed in loocv
        for name in names:
            idxs = [i for i, label in enumerate(y_true) if label == name]
            correct = sum(1 for i in idxs if y_pred[i] == name)
            total = len(idxs)
            person_acc = correct / total * 100 if total > 0 else 0.0
            per_person[name].append(person_acc)

            # Print so you can see the values as it runs
            print(f"  {name}: {t:.2f} → {person_acc:.1f}%")

    # Plot threshold analysis
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    # Left plot - recognition metrics
    for metric in ['accuracy', 'precision', 'recall', 'f1']:
        ax1.plot(results['threshold'],
                [v * 100 for v in results[metric]],
                marker='o', label=metric.capitalize())

    ax1.axvline(x=0.65, color='red', linestyle=':', label='Current threshold')
    ax1.set_xlabel('Threshold')
    ax1.set_ylabel('Percentage (%)')
    ax1.set_title('Recognition Metrics vs Threshold')
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    # Right plot - unknown rate
    ax2.plot(results['threshold'],
            [v * 100 for v in results['unknown_rate']],
            marker='s', color='orange', label='Unknown Rate')

    ax2.axvline(x=0.65, color='red', linestyle=':', label='Current threshold')
    ax2.set_xlabel('Threshold')
    ax2.set_ylabel('Percentage (%)')
    ax2.set_title('Unknown Rate vs Threshold')
    ax2.legend()
    ax2.grid(True, alpha=0.3)

    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    out_path = f'threshold_analysis_{timestamp}.png'
    plt.tight_layout()
    plt.savefig(out_path, dpi=120)
    print(f"[INFO] Threshold analysis saved to [{out_path}]")

    # Plot per-person accuracy across thresholds
    # One line per person showing how their individual accuracy changes with threshold
    fig, ax = plt.subplots(figsize=(12, 6))
    colours = plt.cm.tab10(np.linspace(0, 1, len(names)))

    for name, colour in zip(names, colours):
        ax.plot(results['threshold'], per_person[name],
                marker='o', label=name, color=colour)

    ax.axvline(x=0.65, color='red', linestyle=':', label='Current threshold')
    ax.set_xlabel('Threshold')
    ax.set_ylabel('Accuracy (%)')
    ax.set_title('Per-Person Recognition Accuracy vs Threshold')
    ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    ax.set_ylim([0, 105])
    ax.grid(True, alpha=0.3)

    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    out_path = f'per_person_accuracy_{timestamp}.png'
    plt.tight_layout()
    plt.savefig(out_path, dpi=120)
    print(f"[INFO] Per-person accuracy plot saved to [{out_path}]")

def compare_augmentation(names: list[str], database_aug: dict, thresholds: np.ndarray):
    """
    Run threshold sweep LOOCV on both augmented and non-augmented databases,
    then plot side-by-side metric comparisons and compute RMSE between them.
    """
    # Check non-augmented database exists — only generated with --compare_aug flag
    if not os.path.exists('embeddings_noaug.pkl'):
        print("[WARN] embeddings_noaug.pkl not found. Run face_system.py --rebuild --compare_aug first.")
        return

    with open('embeddings_noaug.pkl', 'rb') as f:
        database_noaug: dict = pickle.load(f)

    names_noaug = sorted(database_noaug.keys())

    # Results storage for both databases across all thresholds
    metrics = ['accuracy', 'precision', 'recall', 'f1', 'unknown_rate']
    results_aug   = {m: [] for m in metrics}
    results_noaug = {m: [] for m in metrics}
    results_aug['threshold']   = []
    results_noaug['threshold'] = []

    for t in thresholds:
        print(f"Comparing threshold {t:.2f}...")

        # Run LOOCV on augmented database
        y_true_aug, y_pred_aug = [], []
        _, acc, pre, rec, f1, unk = loocv(names, y_true_aug, y_pred_aug, t, database_aug)
        results_aug['threshold'].append(t)
        results_aug['accuracy'].append(acc)
        results_aug['precision'].append(pre)
        results_aug['recall'].append(rec)
        results_aug['f1'].append(f1)
        results_aug['unknown_rate'].append(unk)

        # Run LOOCV on non-augmented database
        y_true_noaug, y_pred_noaug = [], []
        _, acc, pre, rec, f1, unk = loocv(names_noaug, y_true_noaug, y_pred_noaug, t, database_noaug)
        results_noaug['threshold'].append(t)
        results_noaug['accuracy'].append(acc)
        results_noaug['precision'].append(pre)
        results_noaug['recall'].append(rec)
        results_noaug['f1'].append(f1)
        results_noaug['unknown_rate'].append(unk)

    # Print RMSE table — measures average difference between augmented and non-augmented
    # across all thresholds for each metric. Higher RMSE = augmentation had more impact.
    print("\n══════════════════════════════════════════════════════════════")
    print("  Augmentation Comparison — RMSE across threshold sweep")
    print("══════════════════════════════════════════════════════════════")
    print(f"  {'Metric':<20} {'RMSE':>10} {'Avg Aug':>10} {'Avg NoAug':>10}")
    print("─" * 54)
    for m in metrics:
        aug_vals   = np.array(results_aug[m])
        noaug_vals = np.array(results_noaug[m])
        # RMSE between the two curves — how much augmentation shifts each metric
        rmse = np.sqrt(np.mean((aug_vals - noaug_vals) ** 2)) * 100
        avg_aug   = np.mean(aug_vals) * 100
        avg_noaug = np.mean(noaug_vals) * 100
        print(f"  {m.capitalize():<20} {rmse:>9.3f}% {avg_aug:>9.2f}% {avg_noaug:>9.2f}%")
    print("══════════════════════════════════════════════════════════════\n")

    # Plot — one subplot per metric, augmented vs non-augmented on same axes
    fig, axes = plt.subplots(2, 3, figsize=(18, 10))
    axes = axes.flatten()

    for idx, m in enumerate(metrics):
        ax = axes[idx]
        ax.plot(results_aug['threshold'],
                [v * 100 for v in results_aug[m]],
                marker='o', color='blue', label='Augmented')
        ax.plot(results_noaug['threshold'],
                [v * 100 for v in results_noaug[m]],
                marker='s', color='orange', linestyle='--', label='No Augmentation')

        # Shade the difference between the two curves to visualise impact
        ax.fill_between(results_aug['threshold'],
                        [v * 100 for v in results_aug[m]],
                        [v * 100 for v in results_noaug[m]],
                        alpha=0.15, color='green', label='Difference')

        # RMSE annotation on each subplot
        aug_vals   = np.array(results_aug[m])
        noaug_vals = np.array(results_noaug[m])
        rmse = np.sqrt(np.mean((aug_vals - noaug_vals) ** 2)) * 100
        ax.text(0.05, 0.05, f'RMSE={rmse:.3f}%',
                transform=ax.transAxes, fontsize=9,
                bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

        ax.axvline(x=0.65, color='red', linestyle=':', label='Current threshold')
        ax.set_xlabel('Threshold')
        ax.set_ylabel('Percentage (%)')
        ax.set_title(f'{m.capitalize()} vs Threshold')
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.3)
        ax.set_ylim([0, 105])

    # Hide the unused 6th subplot since we only have 5 metrics
    axes[5].set_visible(False)

    plt.suptitle('Augmented vs Non-Augmented Database Comparison', fontsize=14, y=1.02)
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    out_path = f'augmentation_comparison_{timestamp}.png'
    plt.tight_layout()
    plt.savefig(out_path, dpi=120, bbox_inches='tight')
    print(f"[INFO] Augmentation comparison plot saved to [{out_path}]")
    
if __name__ == '__main__':
    names, database, filename_map = database_load()
    parser = argparse.ArgumentParser()
    parser.add_argument('--threshold', type=float, default=0.65)
    parser.add_argument('--compare_aug', action='store_true', help='Compare augmented vs non-augmented database metrics')
    args = parser.parse_args()
    evaluate(args.threshold, names, database, filename_map )
    evaluate_threshold_range(np.linspace(0.45,0.95,10),  names, database)

    # Run augmentation comparison if requested and embeddings_noaug.pkl exists
    if args.compare_aug:
        compare_augmentation(names, database, np.linspace(0.45, 0.95, 10))